# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01e8d3ffea2e274c191cd976bc168ed10e49da69899271929b828e5ec3f5c54e5503685636f345a1e84664df1e50980c00b363517ad9acfe3e1d35b93415a956

test:
  secret_key_base: 5434b36ae431fe289d33966554b1f9fa7de17ed80fa28745068641aef5c8b4438d6f4ffa3b3870c56847950b8c4968e8473df6419873b6f6c14a2446e97f55d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
